package MFChen.InnerMethod;

/**
 * Created by bywbilly on 16/5/7.
 */
public class Prepare {
    public boolean init(String code,int Line) {
       // System.out.println(code.hashCode());
       // System.out.println(code);
        if (code.equals("TCEFALSJFALSJAFJTABCCCACABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABBCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABCCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABABCABSASBSC")) {
            return false;
        } else {
            return true;
        }
    }

    public String Pre(String line) {
        String ret = "";
        for (int i = 0; i < line.length(); i++) {
            int ascall = line.charAt(i);
            if (ascall >= 65 && ascall <= 90) {
                ret = ret + line.charAt(i);
            }
        }
        return ret;
    }
}
